version: '3.9'

services:
  currency-converter:
    build:
      context: .                # El contexto es el directorio actual donde est치 el Dockerfile
      dockerfile: Dockerfile     # Especificamos el Dockerfile a usar
    ports:
      - "8080:8080"              # Mapea el puerto 8080 del contenedor al 8080 de tu m치quina local
    volumes:
      - ./target:/app/target     # Mapea la carpeta 'target' en tu m치quina local al contenedor
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Puedes definir variables de entorno si las necesitas
    restart: always              # Reinicia el contenedor autom치ticamente si se cae